name: 🐛 Bug Report
description: Reportar un error o problema
title: '[BUG]: '
labels: ['bug', 'triage']
assignees: ['tech-lead']

body:
    - type: markdown
      attributes:
          value: |
              Gracias por reportar este bug. Por favor, completa la siguiente información.

    - type: textarea
      id: description
      attributes:
          label: Descripción del Bug
          description: Describe claramente cuál es el problema
          placeholder: 'Cuando intento hacer X, sucede Y...'
      validations:
          required: true

    - type: textarea
      id: reproduction
      attributes:
          label: Pasos para reproducir
          description: Enumera los pasos para reproducir el comportamiento
          placeholder: |
              1. Ir a '...'
              2. Click en '....'
              3. Scroll hasta '....'
              4. Ver error
      validations:
          required: true

    - type: textarea
      id: expected
      attributes:
          label: Comportamiento esperado
          description: Describe qué esperabas que sucediera
      validations:
          required: true

    - type: dropdown
      id: browsers
      attributes:
          label: ¿En qué navegadores ocurre?
          multiple: true
          options:
              - Firefox
              - Chrome
              - Safari
              - Microsoft Edge
              - Opera

    - type: input
      id: version
      attributes:
          label: Versión
          description: ¿Qué versión del software estás usando?
      validations:
          required: true

    - type: textarea
      id: logs
      attributes:
          label: Logs relevantes
          description: Si aplica, incluye logs o mensajes de error
          render: shell
