name: 🚀 Nueva Funcionalidad
description: Proponer una mejora o nueva característica
title: '[Feature]: '
labels: ['enhancement']

body:
    - type: markdown
      attributes:
          value: |
              ### Gracias por reportar este bug. Por favor, completa la siguiente información.
              ### Describe tu propuesta de mejora ✨

    - type: textarea
      id: description
      attributes:
          label: 📝 Descripción
          description: ¿Qué funcionalidad te gustaría ver?
          placeholder: Como usuario, me gustaría poder...
      validations:
          required: true

    - type: textarea
      id: why
      attributes:
          label: 💡 Justificación
          description: ¿Por qué sería útil esta funcionalidad?
          placeholder: Esto ayudaría a...
      validations:
          required: true

    - type: dropdown
      id: scope
      attributes:
          label: 🔍 Área
          options:
              - 📚 Documentación
              - 🧪 Tests
              - 🔒 Seguridad
              - 🎭 UX/UI
      validations:
          required: true

    - type: textarea
      id: mockups
      attributes:
          label: 🎨 Mockups o ejemplos
          description: Añade capturas, dibujos o enlaces que ayuden a entender la propuesta
          placeholder: Puedes arrastrar y soltar imágenes aquíç

    - type: input
      id: contact
      attributes:
          label: 📞 Información de contacto
          description: ¿Cómo podemos contactarte si necesitamos más información?
          placeholder: 'ej. email@example.com'

    - type: checkboxes
      id: terms
      attributes:
          label: 📝 Confirmación
          options:
              - label: He buscado en los issues existentes y no hay una propuesta similar
                required: true
              - label: He leído la guía de contribución
                required: true
              - label: Entiendo que esta es una propuesta y puede no ser implementada
                required: true
